# Generated by Django 5.1.1 on 2025-10-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_type',
            field=models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], default='Inclusive', max_length=50),
        ),
    ]
