# Generated by Django 5.1.1 on 2025-10-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order_vat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_code',
        ),
    ]
