# Generated by Django 5.1.1 on 2025-10-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
