# Generated by Django 5.1.1 on 2025-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order_number_of_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
